@startuml
participant User
participant GameBoardComponent
participant GameController
participant GameBoard
participant ColorCounter
participant AnimationService
participant ColorCounterComponent

User -> GameBoardComponent : onPanelClick(panelId)
GameBoardComponent -> GameController : applyColorChange(panelId)
GameController -> GameBoard : getPanelsToChangeColor(panelId)
GameBoard --> GameController : return panelsToChangeColor
GameController --> GameBoardComponent : initiatePanelColorChange(panelsToChangeColor)
loop Until panelsToChangeColor is empty
    GameBoardComponent -> AnimationService : startAnimation(panel)
    AnimationService --> GameBoardComponent : emit('animationStart')
    GameBoardComponent -> GameController : updateColorCounterAndGameBoard(panel)
    GameController -> GameBoard : changePanelColor(panel)
    GameBoard --> GameController : confirmUpdate
    GameController -> GameBoardComponent : updateGameBoardDisplay(panels)
    GameBoardComponent --> GameController : confirmDisplayUpdate
    GameController -> ColorCounter : updateColorCounter()
    ColorCounter --> GameController : confirmUpdate
    GameController -> ColorCounterComponent : updateColorCounterDisplay(newColorCounterValues)
    ColorCounterComponent --> GameController : confirmDisplayUpdate
    GameController -> GameBoardComponent : confirmUpdateDisplayOfPanel(panel)
    GameBoardComponent --> GameBoardComponent : removePanelFromList(panel)
end
@enduml
