@startuml
participant User
participant AnimationService
participant GameBoardComponent
participant GameController
participant GameBoard
participant ColorCounter
participant ColorCounterComponent

User -> GameBoardComponent : onPanelClick(panelId)
GameBoardComponent -> AnimationService: handlePanelClick(panelId)
AnimationService->GameController: applyColorChange(panelId) 
activate GameController
GameController -> GameBoard : getPanelsToChangeColor(panelId)
GameBoard --> GameController : return panelsToChangeColor
GameController --> AnimationService : initiatePanelColorChange(panelsToChangeColor)
deactivate GameController
loop Until panelsToChangeColor is empty
    AnimationService -> GameController : updateGameBoard(panel)
    activate GameController
    GameController -> GameBoard : changePanelColor(panel)
    GameBoard --> GameController
    deactivate GameController
    AnimationService -> GameBoardComponent : updateGameBoardDisplay(panels)
    AnimationService -> GameController : updateColorCounter()
    activate GameController
    GameController -> ColorCounter : changeColorCounter()
    ColorCounter --> GameController
    deactivate GameController
    AnimationService-> ColorCounterComponent : updateColorCounterDisplay(newColorCounterValues)
    AnimationService--> AnimationService: removePanelFromChangeColorList(panel)
end
@enduml